spring.application.name=NextMovie

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/NextMovie
spring.datasource.username=postgres
spring.datasource.password=Dalai@123

server.servlet.context-path=/api/v1

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secretKey=ljdsaofdoweuroq234jkffsalmfkjerwouinslfjsfmafjoaiefjasfasfjasfa

omdb.api.url=https://www.omdbapi.com/
omdb.api.key=93824a93

#omdb.api.key=${OMDB_API_KEY}
